src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Exception;
use JetBrains\PhpStorm\Internal\LanguageLevelTypeAware;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"email"}, message="Il existe déja un compte avec cet email")
 * @UniqueEntity("Pseudo", message="Il existe déja un compte avec ce Pseudo")
 * @Vich\Uploadable
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface, \Serializable
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\Email(message="user.email.notvalid")
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @Assert\NotBlank(message="not_blank")
     * @Assert\Length(min=2, max=25, minMessage="user.length25", maxMessage="user.length25")
     * @ORM\Column(type="string", length=25)
     */
    private $nom;

    /**
     * @Assert\NotBlank(message="not_blank")
     * @Assert\Length(min=2, max=25, minMessage="user.length25", maxMessage="user.length25")
     * @ORM\Column(type="string", length=25)
     */
    private $prenom;

    /**
     * @Assert\Length(max=10, min=10,minMessage="user.tel", maxMessage="user.tel")
     * @ORM\Column(type="string", length=25, nullable=true)
     */
    private $telephone;

    /**
     * @ORM\Column(type="boolean")
     */
    private $actif;

    /**
     * @ORM\OneToMany(targetEntity=Sortie::class, mappedBy="organisateur",cascade={"remove"})
     * @ORM\JoinColumn(onDelete="CASCADE")
     */
    private  $sortiesOrga;

    /**
     * @ORM\ManyToMany(targetEntity=Sortie::class, mappedBy="participant")
     */
    private $sortiesParticipant;

    /**
     * @ORM\Column(type="boolean")
     */
    private $isVerified = false;

    /**
     * @ORM\ManyToOne(targetEntity=Campus::class, inversedBy="users")
     */
    private $Campus;

    /**
     *
     * @Assert\NotBlank(message="not_blank")
     * @Assert\Length(min=2, max=25, minMessage="user.length25", maxMessage="user.length25")
     * @ORM\Column(type="string", length=25, unique = true, nullable = true)
     */
    private $Pseudo;


    public function __construct()
    {
        $this->sortiesOrga = new ArrayCollection();
        $this->sortiesParticipant = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        //$roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getTelephone(): ?string
    {
        return $this->telephone;
    }

    public function setTelephone(?string $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function isActif(): ?bool
    {
        return $this->actif;
    }

    public function setActif(bool $actif): self
    {
        $this->actif = $actif;

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSortiesOrga(): Collection
    {
        return $this->sortiesOrga;
    }

    public function addSorty(Sortie $sorty): self
    {
        if (!$this->sortiesOrga->contains($sorty)) {
            $this->sortiesOrga[] = $sorty;
            $sorty->setOrganisateur($this);
        }

        return $this;
    }

    public function removeSorty(Sortie $sorty): self
    {
        if ($this->sortiesOrga->removeElement($sorty)) {
            // set the owning side to null (unless already changed)
            if ($sorty->getOrganisateur() === $this) {
                $sorty->setOrganisateur(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Sortie>
     */
    public function getSortiesParticipant(): Collection
    {
        return $this->sortiesParticipant;
    }

    public function addSortiesParticipant(Sortie $sortiesParticipant): self
    {
        if (!$this->sortiesParticipant->contains($sortiesParticipant)) {
            $this->sortiesParticipant[] = $sortiesParticipant;
            $sortiesParticipant->addParticipant($this);
        }

        return $this;
    }

    public function removeSortiesParticipant(Sortie $sortiesParticipant): self
    {
        if ($this->sortiesParticipant->removeElement($sortiesParticipant)) {
            $sortiesParticipant->removeParticipant($this);
        }

        return $this;
    }

    public function isVerified(): bool
    {
        return $this->isVerified;
    }

    public function setIsVerified(bool $isVerified): self
    {
        $this->isVerified = $isVerified;

        return $this;
    }

    public function getCampus(): ?Campus
    {
        return $this->Campus;
    }

    public function setCampus(?Campus $Campus): self
    {
        $this->Campus = $Campus;

        return $this;
    }

    public function getPseudo(): ?string
    {
        return $this->Pseudo;
    }

    public function setPseudo(string $Pseudo): self
    {
        $this->Pseudo = $Pseudo;

        return $this;
    }

    /**
     * FILE UPLOAD ATTR
     */

    /**
     * NOTE: This is not a mapped field of entity metadata, just a simple property.
     * @Assert\File(maxSizeMessage="L'image est trop grande, maximun 2Mb", uploadIniSizeErrorMessage="L'image est trop grande, maximun 2Mb")
     * @Vich\UploadableField(mapping="user_img", fileNameProperty="imageName", size="imageSize")
     *
     * @var File|null
     */
    private $imageFile;

    /**
     * @ORM\Column(type="string", nullable=true)
     *
     * @var string|null
     */
    private $imageName;

    /**
     * @ORM\Column(type="integer", nullable=true)
     *
     * @var int|null
     */
    private $imageSize;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     *
     * @var \DateTimeInterface|null
     */
    private $updatedAt;

    /**
     * If manually uploading a file (i.e. not using Symfony Form) ensure an instance
     * of 'UploadedFile' is injected into this setter to trigger the update. If this
     * bundle's configuration parameter 'inject_on_load' is set to 'true' this setter
     * must be able to accept an instance of 'File' as the bundle will inject one here
     * during Doctrine hydration.
     *
     * @param File|\Symfony\Component\HttpFoundation\File\UploadedFile|null $imageFile
     */
    public function setImageFile(?File $imageFile = null): void
    {
        $this->imageFile = $imageFile;

        if (null !== $imageFile) {
            // It is required that at least one field changes if you are using doctrine
            // otherwise the event listeners won't be called and the file is lost
            $this->updatedAt = new \DateTimeImmutable();
        }
    }

    public function getImageFile(): ?File
    {
        return $this->imageFile;
    }

    public function setImageName(?string $imageName): void
    {
        $this->imageName = $imageName;
    }

    public function getImageName(): ?string
    {
        return $this->imageName;
    }

    public function setImageSize(?int $imageSize): void
    {
        $this->imageSize = $imageSize;
    }

    public function getImageSize(): ?int
    {
        return $this->imageSize;
    }

    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,

templates/inc/footer.html.twig
<div class="footer-dark">
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-sm-6 col-md-3 item">
                    <h3>Services</h3>
                    <ul>
                        <li><a href="{{ path('main_home') }}">Accueil</a></li>
                        <li><a href="{{path('app_event_research')}}">Trouvez un évènement</a></li>
                        <li><a href="{{ path('security_login') }}">Connexion</a></li>
                        <li><a href="{{ path('app_register') }}">Inscription</a></li>
                    </ul>
                </div>
                <div class="col-sm-6 col-md-3 item">
                    <h3>A propos</h3>
                    <ul>
                        <li><a href="#">Politique de confidentialité</a></li>
                        <li><a href="#">Notre équipe</a></li>
                        <li><a href="#">Signaler un problème</a></li>
                    </ul>
                </div>
                <div class="col-md-6 item text">
                    <h3>Sortir.com</h3>
                    <p>Sortir.com est une plateforme dédiée aux étudiants des campus de l'ENI école informatique, voulant se changer les idées et rencontrer d'autres personnes autour d'évènements sociaux .</p>
                </div>
                <div class="col item social"><a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a></div>
            </div>
            <p class="copyright">ENI © 2022</p>
        </div>
    </footer>
</div>

templates/inc/gallery.html.twig
<div class="gallary row">

{% if listSortie|length > 0 %}
    {% for sortie in listSortie %}

    {% set placeDispo = sortie.nbInscriptionMax - sortie.participant|length %}

        <div  class="gallary-container col-sm-6 col-lg-3 gallary-item wow fadeIn">

            <img src="{{ asset('assets/imgs/'~ sortie.categorie.backdrop )}}" class="gallary-img">

            <div class="gallary-info">
                <img class="picto" src="{{ asset('assets/imgs/picto/'~ sortie.categorie.picto )}}" alt="">
                <h4 class="info-title">{{ sortie.nom }}</h4>
                <p>{{ sortie.dateHeureDebut |date("d/m/y H:i") }}</p>
                <div class="info-ville">
                    <p><i class="ti-location-pin"></i> {{ sortie.lieu.ville.nom }}</p>
                </div>
                <p> {{ placeDispo }} places disponibles</p>




                {% if sortie.etat.id in [2,4]  %}
                    <p class="btn btn-dark">Sortie terminée</p>

                {% elseif sortie.etat.id == 3 %}
                    <p class="btn btn-primary">événement en cour</p>
                {% elseif sortie.etat.id == 5 %}
                    <p class="btn btn-dark">Sortie Annulée</p>
                {% elseif sortie.etat.id == 6 %}
                    {% if app.user and sortie in app.user.sortiesParticipant %}
                        <p class="btn btn-info">inscrit</p>
                     {% else %}
                         <p class="btn btn-primary">inscription Ouverte</p>
                    {% endif %}
                {% elseif sortie.etat.id == 7 %}

                    {% if app.user and sortie in app.user.sortiesParticipant %}
                        <p class="btn btn-primary">inscrit/inscription cloturée</p>
                    {% else %}
                        <p class="btn btn-dark">inscription cloturée</p>
                    {% endif %}
                 {% endif %}


            </div>

            <div class="gallary-overlay">
                <a class="btn btn-primary m-1" href="{{ path('sortie_detail', { 'id': sortie.id}) }}" >Plus d'infos</a>
                {% if sortie.etat.id not in [2,4,5]%}
                    {% if app.user %}
                        {% if sortie in app.user.sortiesParticipant %}
                            <a class="btn btn-primary m-1" href="{{ path('sortie_desister',{ 'id': sortie.id}) }}">se désister</a>
                        {% else %}

                            {% if sortie.etat.id == 7 %}
                                <p class="btn btn-primary disabled m-1" > Inscription Cloturé</p>
                            {% else %}
                                <a class="btn btn-primary m-1" href="{{ path('sortie_inscription',{ 'id': sortie.id}) }}">S'inscrire</a>
                            {% endif %}
                        {% endif %}
                    {% endif %}
                {% endif %}

            </div>

        </div>

{% endfor %}
{% else %}
  <h3 style="margin:auto;" >Aucun évènement trouvé</h3>
{% endif %}
</div>

templates/inc/galleryProfile.html.twig
<div class="gallary row position-relative pt-4 flex flex-column justify-content-center align-items-center">
    <h2>Evènement inscrit :</h2>
    <div class="flex flex- justify-content-center flex-wrap">
        {% for sortie in user.sortiesParticipant %}
            {% set placeDispo = sortie.nbInscriptionMax - sortie.participant|length %}
            <div  class="gallary-container col-sm-6 col-lg-3 gallary-item wow fadeIn">
                <img src="{{ asset('assets/imgs/'~ sortie.categorie.backdrop )}}" class="gallary-img">
                <div class="gallary-info">
                    <img class="picto" src="{{ asset('assets/imgs/picto/'~ sortie.categorie.picto )}}" alt="">
                    <h4 class="info-title">{{ sortie.nom }}</h4>
                    <p>{{ sortie.dateHeureDebut |date("d/m/y H:i") }}</p>
                    <div class="info-ville">

                        <p><i class="ti-location-pin"></i> {{ sortie.lieu.ville.nom }}</p>
                    </div>
                    <p> {{ placeDispo }} places disponibles</p>

                    {% if app.user and sortie in app.user.sortiesParticipant %}
                        <p class="btn btn-primary">inscrit</p>
                    {% endif %}
                </div>
                <a href="{{ path('sortie_detail', { 'id': sortie.id}) }}" class="gallary-overlay">
                    <i class="gallary-icon ti-plus"></i>
                </a>
            </div>
        {% endfor %}
    </div>

</div>





    <div class="gallary row position-relative pt-4 flex flex-column justify-content-center align-items-center">
        <h2>Sortie organisé :</h2>
        <div class="flex flex- justify-content-center flex-wrap">
            {% for sortie in user.sortiesOrga %}
                {% set placeDispo = sortie.nbInscriptionMax - sortie.participant|length %}
                <div  class="gallary-container col-sm-6 col-lg-3 gallary-item wow fadeIn">
                    <img src="{{ asset('assets/imgs/'~ sortie.categorie.backdrop )}}" class="gallary-img">
                    <div class="gallary-info">
                        <img class="picto" src="{{ asset('assets/imgs/picto/'~ sortie.categorie.picto )}}" alt="">
                        <h4 class="info-title">{{ sortie.nom }}</h4>
                        <p>{{ sortie.dateHeureDebut |date("d/m/y H:i") }}</p>
                        <div class="info-ville">

                            <p><i class="ti-location-pin"></i> {{ sortie.lieu.ville.nom }}</p>
                        </div>
                        <p> {{ placeDispo }} places disponibles</p>

                        {% if app.user and sortie in app.user.sortiesOrga %}
                            <p class="btn btn-primary">Organisé</p>
                        {% endif %}
                    </div>
                    <a href="{{ path('sortie_detail', { 'id': sortie.id}) }}" class="gallary-overlay">
                        <i class="gallary-icon ti-plus"></i>
                    </a>
                </div>
            {% endfor %}
        </div>

    </div>



    {% if user == app.user  %}
            <div class="gallary row position-relative pt-4 flex flex-column justify-content-center align-items-center">
                <h2>Sortie non publié :</h2>
                <div class="flex flex- justify-content-center flex-wrap">
                    {% for sortie in user.sortiesOrga %}
                        {% if sortie.etat.id == 1 %}
                            {% set placeDispo = sortie.nbInscriptionMax - sortie.participant|length %}
                            <div  class="gallary-container col-sm-6 col-lg-3 gallary-item wow fadeIn">
                                <img src="{{ asset('assets/imgs/'~ sortie.categorie.backdrop )}}" class="gallary-img">
                                <div class="gallary-info">
                                    <img class="picto" src="{{ asset('assets/imgs/picto/'~ sortie.categorie.picto )}}" alt="">
                                    <h4 class="info-title">{{ sortie.nom }}</h4>
                                    <p>{{ sortie.dateHeureDebut |date("d/m/y H:i") }}</p>
                                    <div class="info-ville">

                                        <p><i class="ti-location-pin"></i> {{ sortie.lieu.ville.nom }}</p>
                                    </div>
                                    <p> {{ placeDispo }} places disponibles</p>
                                    <p class="btn btn-primary">Brouillon</p>
                                </div>
                                <a href="{{ path('sortie_detail', { 'id': sortie.id}) }}" class="gallary-overlay">
                                    <i class="gallary-icon ti-plus"></i>
                                </a>
                            </div>
                        {% endif %}
                    {% endfor %}
            </div>
</div>
    {% endif %}

templates/inc/nav.html.twig
<nav class="custom-navbar navbar navbar-expand-lg navbar-dark fixed-top" data-spy="affix" data-offset-top="10">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a class="navbar-brand m-auto" href="{{ path('main_home') }}">
            <img src="{{ asset('assets/imgs/logo.svg') }}" class="brand-img" alt="">
        </a>
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{{path('app_event_research')}}">Trouvez un évènement</a>
            </li>

            {% if is_granted('ROLE_ADMIN') %}

            <li class="nav-item">
                <a class="nav-link" href="{{ path('ville_') }}">Ville</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('campus_') }}">Campus</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ path('profile_list') }}">Liste utilisateurs</a>
            </li>
            {% endif %}



           {% if app.user %}

            {% if is_granted('ROLE_USER') %}
            <li class="nav-item">
                 <a class="nav-link" href="{{ path('profile_edit_details') }}">Mon profil</a>
            </li>
             {% endif%}

            <li class="nav-item">
                <a class="nav-link" href={{ path('security_logout') }}>Déconnection</a>
            </li>
            {% if is_granted('ROLE_USER') %}
            <li class="nav-item">
                <a href="{{ path('sortie_cree') }}" class="btn btn-primary ml-xl-4">Créer un évènement</a>
            </li>
             {% endif%}
           {% else %}
               <li class="nav-item">
                   <a class="btn btn-primary ml-xl-4" href="{{ path('security_login') }}">Connexion</a>
               </li>
           {% endif %}

        </ul>
    </div>

</nav>
{% if app.user %}
    <p style="padding-right: 50px; width: 100%;text-align: right">Bonjour {{ app.user.pseudo }}</p>
{% endif %}

templates/inc/navAdmin.html.twig
<nav class="custom-navbar navbar navbar-expand-lg navbar-dark fixed-top" data-spy="affix" data-offset-top="10">
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <a class="navbar-brand m-auto" href="{{ path('main_home') }}">
            <img src="{{ asset('assets/imgs/logo.svg') }}" class="brand-img" alt="">




        </a>
        <ul class="navbar-nav">


            <li class="nav-item">
                <a class="nav-link" href="#testmonial">Trouvez un évènement</a>
            </li>



            {% if is_granted('ROLE_ADMIN') %}

                <li class="nav-item">
                    <a class="nav-link" href="#testmonial">Ville</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#testmonial">Campus</a>
                </li>
            {% endif %}



            {% if app.user %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ path('profile_list') }}">Liste Utilisateurs</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{{ path('profile_edit_details') }}">Mon profil</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href={{ path('security_logout') }}>Déconnection</a>
                </li>
                <li class="nav-item">
                    <a href="{{ path('sortie_cree') }}" class="btn btn-primary ml-xl-4">Créer une évènement</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="btn btn-primary ml-xl-4" href="{{ path('security_login') }}">Connexion</a>
                </li>
            {% endif %}

        </ul>
    </div>
</nav>